#!/bin/bash

PACKAGES=(
    android.autoinstalls.config.samsung
    com.android.bips
    com.android.calllogbackup
    com.android.egg
    com.android.hotwordenrollment.okgoogle
    com.android.hotwordenrollment.xgoogle
    com.android.microdroid.empty_payload
    com.android.printspooler
    com.android.providers.partnerbookmarks
    com.android.role.notes.enabled
    com.android.theme.font.notoserifsource
    com.android.traceur
    com.android.virtualization.terminal
    com.android.virtualmachine.res
    com.facebook.appmanager
    com.facebook.services
    com.facebook.system
    com.google.android.adservices.api
    com.google.android.apps.accessibility.voiceaccess
    com.google.android.apps.aiwallpapers
    com.google.android.apps.restore
    com.google.android.as
    com.google.android.federatedcompute
    com.google.android.feedback
    com.google.android.gms.supervision
    com.google.android.ondevicepersonalization.services
    com.google.android.onetimeinitializer
    com.google.android.printservice.recommendation
    com.google.ar.core
    com.google.audio.hearing.visualization.accessibility.scribe
    com.google.mainline.adservices
    com.knox.vpn.proxyhandler
    com.microsoft.appmanager
    com.microsoft.skydrive
    com.monotype.android.font.foundation
    com.monotype.android.font.samsungone
    com.mygalaxy.service
    com.qti.qcc
    com.qti.snapdragon.qdcm_ff
    com.samsung.aasaservice
    com.samsung.android.accessibility.talkback
    com.samsung.android.aircommandmanager
    com.samsung.android.allshare.service.mediashare
    com.samsung.android.app.camera.sticker.facearavatar.preload
    com.samsung.android.app.dressroom
    com.samsung.android.app.earphonetypec
    com.samsung.android.app.omcagent
    com.samsung.android.app.parentalcare
    com.samsung.android.app.sharelive
    com.samsung.android.app.telephonyui.esimclient
    com.samsung.android.app.watchmanagerstub
    com.samsung.android.aremoji
    com.samsung.android.aremojieditor
    com.samsung.android.authfw
    com.samsung.android.bbc.bbcagent
    com.samsung.android.beaconmanager
    com.samsung.android.bixby.agent
    com.samsung.android.bixbyvision.framework
    com.samsung.android.bixby.wakeup
    com.samsung.android.cameraxservice
    com.samsung.android.carkey
    com.samsung.android.coldwalletservice
    com.samsung.android.da.daagent
    com.samsung.android.dbsc
    com.samsung.android.dck.timesync
    com.samsung.android.dkey
    com.samsung.android.dsms
    com.samsung.android.easysetup
    com.samsung.android.fast
    com.samsung.android.forest
    com.samsung.android.game.gametools
    com.samsung.android.game.honeyplayplus
    com.samsung.android.hdmapp
    com.samsung.android.inputshare
    com.samsung.android.ipsgeofence
    com.samsung.android.kidsinstaller
    com.samsung.android.knox.analytics.uploader
    com.samsung.android.knox.attestation
    com.samsung.android.knox.containercore
    com.samsung.android.knox.kpecore
    com.samsung.android.knox.pushmanager
    com.samsung.android.knox.zt.framework
    com.samsung.android.mapsagent
    com.samsung.android.mcfds
    com.samsung.android.mdecservice
    com.samsung.android.mdm
    com.samsung.android.mdx
    com.samsung.android.mdx.kit
    com.samsung.android.mocca
    com.samsung.android.mydevice
    com.samsung.android.networkdiagnostic
    com.samsung.android.rubin.app
    com.samsung.android.samsungpass
    com.samsung.android.samsungpassautofill
    com.samsung.android.scloud
    com.samsung.android.scpm
    com.samsung.android.sdm.config
    com.samsung.android.server.wifi.mobilewips
    com.samsung.android.service.peoplestripe
    com.samsung.android.service.stplatform
    com.samsung.android.shortcutbackupservice
    com.samsung.android.smartsuggestions
    com.samsung.android.smartswitchassistant
    com.samsung.android.stickercenter
    com.samsung.android.svcagent
    com.samsung.android.visionintelligence
    com.samsung.android.visualars
    com.samsung.faceservice
    com.samsung.gpuwatchapp
    com.samsung.knox.securefolder
    com.samsung.oda.service
    com.samsung.safetyinformation
    com.samsung.sait.sohservice
    com.samsung.SMT.lang_de_de_f00
    com.samsung.SMT.lang_de_de_g01
    com.samsung.SMT.lang_de_de_l01
    com.samsung.SMT.lang_es_es_f00
    com.samsung.SMT.lang_es_es_g01
    com.samsung.SMT.lang_es_es_l01
    com.samsung.SMT.lang_es_mx_f00
    com.samsung.SMT.lang_fr_fr_f00
    com.samsung.SMT.lang_hi_in_f00
    com.samsung.SMT.lang_it_it_f00
    com.samsung.SMT.lang_th_th_f00
    com.samsung.SMT.lang_vi_vn_f00
    com.samsung.storyservice
    com.sec.android.app.billing
    com.sec.android.app.bluetoothagent
    com.sec.android.app.chromecustomizations
    com.sec.android.app.factorykeystring
    com.sec.android.app.hwmoduletest
    com.sec.android.app.kidshome
    com.sec.android.app.magnifier
    com.sec.android.app.parser
    com.sec.android.app.servicemodeapp
    com.sec.android.app.setupwizardlegalprovider
    com.sec.android.app.uwbtest
    com.sec.android.app.vepreload
    com.sec.android.app.ve.vebgm
    com.sec.android.app.wlantest
    com.sec.android.autodoodle.service
    com.sec.android.CcInfo
    com.sec.android.diagmonagent
    com.sec.android.easyMover
    com.sec.android.easyMover.Agent
    com.sec.android.easyonehand
    com.sec.android.iaft
    com.sec.android.mimage.avatarstickers
    com.sec.android.RilServiceModeApp
    com.sec.android.smartfpsadjuster
    com.sec.android.widgetapp.easymodecontactswidget
    com.sec.app.RilErrorNotifier
    com.sec.bcservice
    com.sec.enterprise.knox.cloudmdm.smdms
    com.sec.epdgtestapp
    com.sec.facatfunction
    com.sec.factory.camera
    com.sec.hearingadjust
    com.sec.imslogger
    com.sec.location.nfwlocationprivacy
    com.sec.location.nsflp2
    com.sec.modem.settings
    com.sec.spp.push
    com.sem.factoryapp
    com.swiftkey.swiftkeyconfigurator
    com.touchtype.swiftkey
    com.wizzair.WizzAirApp
    com.wsomacp
)

echo "Starting cleanup of ${#PACKAGES[@]} packages..."

INSTALLED_PACKAGES=$(adb shell pm list packages --user 0 | tr -d '\r')
REMOVED_ANY=false

for pkg in "${PACKAGES[@]}"; do
    if echo "$INSTALLED_PACKAGES" | grep -qFx "package:$pkg"; then
        echo "Removing $pkg..."
        adb shell pm uninstall -k --user 0 "$pkg"
        REMOVED_ANY=true
    else
        echo "Skipping $pkg - not installed"
    fi
done

if [ "$REMOVED_ANY" = true ]; then
    echo "Cleanup complete! Reboot phone."
else
    echo "Cleanup complete! No changes made."
fi
